### ISSUE TITLE
video_tag_spec.rb doesn't have "px" in attributes of "width" and "height"

### ISSUE THREAD

**Issue by MarikoJanes** [learn-co-curriculum/phase-1-embedded-videos-lab#7]
### Canvas Link

https://learning.flatironschool.com/courses/5178/assignments/172129?module_item_id=376111

### Concern

While `README.md` says to add attributes of `width="600px` and `height="400px`, `video_tag_spec.rb` file doesn't have "px" in its test description.

### Suggested Changes

Change the test description of `video_tag_spec.rb` file to `600px` and `400px`.

**Comment by lizbur10** [comment]
Hi @MarikoJanes ! Thanks for bringing this to our attention. The error has been fixed 💙
